//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyHouse_bilet18
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class УютныйДомEntities : DbContext
    {
        public УютныйДомEntities()
            : base("name=УютныйДомEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<Покупка> Покупка { get; set; }
        public virtual DbSet<СоставПокупки> СоставПокупки { get; set; }
    }
}
