//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozyHouse_bilet18
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставПокупки
    {
        public int Код { get; set; }
        public Nullable<int> Материал { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Длина { get; set; }
        public Nullable<double> Сумма { get; set; }
        public Nullable<int> Покупка { get; set; }
    
        public virtual Материал Материал1 { get; set; }
        public virtual Покупка Покупка1 { get; set; }
    }
}
